export const actionTypes = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    REGISTER: "REGISTER",
    GET_AUTH_USER: "GET_AUTH_USER",
    SET_AUTH_USER: "SET_AUTH_USER",
    GET_USER_PERMISSIONS: "GET_USER_PERMISSIONS",
    SET_USER_PERMISSIONS: "SET_USER_PERMISSIONS",
    // SET_FORGOT_PASSWORD_EMAIL: "auth/SET_FORGOT_PASSWORD_EMAIL"
  };